set -g default-terminal "tmux-256color"
set -g xterm-keys on
set -as terminal-overrides ",xterm*:Tc"
set -s extended-keys off
# set -s extended-keys-format csi-u
set -as terminal-features ",xterm-ghostty:extkeys"
set -as terminal-features ",xterm-ghostty:RGB"
set -as terminal-features ",xterm*:extkeys"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind r
bind r source-file ~/.tmux.conf

unbind x
bind x kill-window

set -g mouse on

set -g mode-keys vi
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @dracula-show-powerline true
set -g @dracula-battery-colors "dark_purple white"
set -g @dracula-weather-colors "green dark_gray"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Shift + I to reload
run '~/.tmux/plugins/tpm/tpm'
